=== bartoszkubicki/message-queue/etc/queue_declaration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * @author Bartosz Kubicki
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="argumentType" abstract="true" mixed="true">
        <xs:attribute name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="argumentsType">
        <xs:sequence>
            <xs:element name="argument" type="argumentType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="argumentItemName">
                    <xs:selector xpath="item"/>
                    <xs:field xpath="@name"/>
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="array" mixed="true">
        <xs:complexContent>
            <xs:extension base="argumentType">
                <xs:sequence>
                    <xs:element name="item" type="argumentType" minOccurs="0" maxOccurs="unbounded">
                        <xs:key name="itemName">
                            <xs:selector xpath="item"/>
                            <xs:field xpath="@name"/>
                        </xs:key>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="number">
        <xs:complexContent>
            <xs:extension base="argumentType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="boolean">
        <xs:complexContent>
            <xs:extension base="argumentType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="string">
        <xs:complexContent>
            <xs:extension base="argumentType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="queueDeclarationType">
        <xs:sequence>
            <xs:element type="argumentsType" name="arguments" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="connection" use="optional"/>
        <xs:attribute type="xs:boolean" name="durable" use="optional"/>
        <xs:attribute type="xs:boolean" name="autoDelete" use="optional"/>
    </xs:complexType>

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="queueDeclarationType" name="queue" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-queue-name-connection">
            <xs:annotation>
                <xs:documentation>
                    Queue name must be unique per connection
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="queue"/>
            <xs:field xpath="@name"/>
            <xs:field xpath="@connection"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== bartoszkubicki/message-queue/Test/Integration/_files/dead_letter/queue_declaration.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:BKubicki_MessageQueue:etc/queue_declaration.xsd">
    <queue name="mqi_work" connection="amqp">
        <arguments>
            <argument name="x-dead-letter-exchange" xsi:type="string">mqi.dead_letter</argument>
        </arguments>
    </queue>
    <queue name="mqi_expiring" connection="amqp">
        <arguments>
            <argument name="x-dead-letter-exchange" xsi:type="string">mqi.dead_letter</argument>
            <argument name="x-message-ttl" xsi:type="number">500</argument>
        </arguments>
    </queue>
</config>
